# Generated by Django 4.0.3 on 2022-03-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEmpresaPerrotta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesion',
            new_name='Empresas_asociadas',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='antiguedad',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='default_value', max_length=40),
            preserve_default=False,
        ),
    ]
